### ISSUE TITLE
SVC attribute error

### ISSUE THREAD

**Issue by scottgigante** [ListerLab/HOME#12]
Hello,

`HOME-pairwise` has failed with the following exception:

```
% HOME-pairwise -t CG -i  ../input.tsv  -o ../out -sin -npp 22
Preparing the DMRs from HOME.....
GOOD LUCK !
/wehisan/general/system/bioinf-software/bioinfsoftware/python/python-2.7.11/lib/python2.7/site-packages/statsmodels/stats/weightstats.py:575: RuntimeWarning: invalid value encountered in double_scalars
  zstat = value / std_diff
/wehisan/general/system/bioinf-software/bioinfsoftware/python/python-2.7.11/lib/python2.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator SVC from version pre-0.18 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/wehisan/home/allstaff/g/gigante.s/soft/lister_home/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.4', 'HOME-pairwise')
  File "/usr/local/bioinfsoftware/python/python-2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/bioinfsoftware/python/python-2.7.11/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/wehisan/home/allstaff/g/gigante.s/soft/lister_home/lib/python2.7/site-packages/HOME-0.4-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 452, in <module>

  File "/wehisan/home/allstaff/g/gigante.s/soft/lister_home/lib/python2.7/site-packages/HOME-0.4-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 224, in main

Exception: 'SVC' object has no attribute 'decision_function_shape'
```

My input file is as follows:

```
$ less ../input.tsv
alt	~/path/to/data/alt.summary.home.tsv
ref	~/path/to/data/ref.summary.home.tsv
```

and my data files look like this

```
$ head ~/path/to/data/alt.summary.home.tsv
chr5    149642973       +       CG      34      42
chr9    121883727       +       CG      3       5
chr9    24213925        +       CG      1       3
chr2    180792870       +       CG      5       8
chr1    7779688 +       CG      1       8
chr9    120952088       +       CG      1       2
chr6    97035598        +       CG      2       4
chr3    127312598       +       CG      10      14
chr3    42041023        +       CG      4       7
chr7    74422202        +       CG      5       8
```

Am I doing something wrong?

Thanks!
Scott

**Comment by Akanksha2511** [comment]
Hi Scott, 
Sorry for the error. Could you please check the version of scikit-learn. It should be 0.16.1. 
Thanks, 
Akanksha
