### ISSUE TITLE
Segmentation fault of HOME

### ISSUE THREAD

**Issue by Linhua-Sun** [ListerLab/HOME#13]
Hi: 
    I follow the instructions to install HOME software. But IT will give me segmentation fault (core dumped) error (when using HOME-pairwise or HOME-timeseries). And nothing else.

**Comment by Akanksha2511** [comment]
Hi, 
Are you using virtual env to install it ?. Can you please check if, after installation, you get the help message when you type HOME-pairwise or HOME-timeseries.

**Comment by Linhua-Sun** [comment]
Thank you very much! I didn't use virtual env to install HOME. Since I also use python 2.7. Is it necessary to use virtual env to install? Why? I will try 'virtual env' again. And I didn't get the help messages after the type of HOME-pairwise or HOME-timeseries.

**Comment by Linhua-Sun** [comment]
Sorry, after I retry to install HOME follow the instructions (use the virtual env to install ) completely.  It gives me another error. As following:
```
Traceback (most recent call last):
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.4', 'HOME-pairwise')
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/HOME-pairwise' not found in metadata at '/data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME/HOME.egg-info'
```
Thank you very much!

**Comment by Akanksha2511** [comment]
Hi,  seems like the package is not installed successfully..did you get any error message after running <python setup.py install> also please make sure you cd in the HOME directory before starting the run.

**Comment by Linhua-Sun** [comment]
Hi, you can see it seems that the installation  is successful. I didn't see any error messages duing installation. And sure, I cd into the HOME dir.
```
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to HOME.egg-info/requires.txt
writing HOME.egg-info/PKG-INFO
writing top-level names to HOME.egg-info/top_level.txt
writing dependency_links to HOME.egg-info/dependency_links.txt
reading manifest file 'HOME.egg-info/SOURCES.txt'
writing manifest file 'HOME.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/HOME
copying build/lib/HOME/__init__.py -> build/bdist.linux-x86_64/egg/HOME
copying build/lib/HOME/HOME_functions.py -> build/bdist.linux-x86_64/egg/HOME
copying build/lib/HOME/HOME_timeseries_functions.py -> build/bdist.linux-x86_64/egg/HOME
byte-compiling build/bdist.linux-x86_64/egg/HOME/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/HOME/HOME_functions.py to HOME_functions.pyc
byte-compiling build/bdist.linux-x86_64/egg/HOME/HOME_timeseries_functions.py to HOME_timeseries_functions.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/HOME-timeseries -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/HOME-pairwise -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/HOME-timeseries to 775
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/HOME-pairwise to 775
copying HOME.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying HOME.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying HOME.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying HOME.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying HOME.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/HOME-0.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing HOME-0.4-py2.7.egg
Removing /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/HOME-0.4-py2.7.egg
Copying HOME-0.4-py2.7.egg to /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
HOME 0.4 is already the active version in easy-install.pth
Installing HOME-pairwise script to /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin
Installing HOME-timeseries script to /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin

Installed /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/HOME-0.4-py2.7.egg
Processing dependencies for HOME==0.4
Searching for statsmodels==0.6.1
Best match: statsmodels 0.6.1
Adding statsmodels 0.6.1 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for scikit-learn==0.16.1
Best match: scikit-learn 0.16.1
Adding scikit-learn 0.16.1 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for scipy==0.16.0
Best match: scipy 0.16.0
Adding scipy 0.16.0 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for pandas==0.17.1
Best match: pandas 0.17.1
Adding pandas 0.17.1 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for python-dateutil==2.6.1
Best match: python-dateutil 2.6.1
Adding python-dateutil 2.6.1 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for pytz==2017.3
Best match: pytz 2017.3
Adding pytz 2017.3 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Searching for six==1.11.0
Best match: six 1.11.0
Adding six 1.11.0 to easy-install.pth file

Using /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages
Finished processing dependencies for HOME==0.4
```

**Comment by Akanksha2511** [comment]
Hi, the installation looks fine. Can you please check if your virtual environment (hh) bin contains HOME-pairwise and HOME-timeseries binaries. 
![bin](https://user-images.githubusercontent.com/12772210/33939163-0b64a090-e045-11e7-88d1-debc5e749788.png)

**Comment by Linhua-Sun** [comment]
Yes, you can see it is there: 
```
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin]$pwd
/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin]$l
total 68K
-rwxrwxr-x 1 linhua linhua 9.9K Dec 13 17:22 python
lrwxrwxrwx 1 linhua linhua    6 Dec 13 17:22 python2.7 -> python
lrwxrwxrwx 1 linhua linhua    6 Dec 13 17:22 python2 -> python
-rwxrwxr-x 1 linhua linhua  269 Dec 13 17:22 easy_install-2.7
-rwxrwxr-x 1 linhua linhua  269 Dec 13 17:22 easy_install
-rwxrwxr-x 1 linhua linhua  241 Dec 13 17:22 pip2.7
-rwxrwxr-x 1 linhua linhua  241 Dec 13 17:22 pip2
-rwxrwxr-x 1 linhua linhua  241 Dec 13 17:22 pip
-rwxrwxr-x 1 linhua linhua  248 Dec 13 17:22 wheel
-rw-rw-r-- 1 linhua linhua 1.2K Dec 13 17:22 activate_this.py
-rw-rw-r-- 1 linhua linhua 2.2K Dec 13 17:22 activate.fish
-rw-rw-r-- 1 linhua linhua 1.1K Dec 13 17:22 activate.csh
-rw-rw-r-- 1 linhua linhua 2.1K Dec 13 17:22 activate
-rwxrwxr-x 1 linhua linhua 2.4K Dec 13 17:22 python-config
-rwxrwxr-x 1 linhua linhua  793 Dec 13 17:27 f2py
-rwxrwxr-x 1 linhua linhua  201 Dec 13 20:07 HOME-pairwise
-rwxrwxr-x 1 linhua linhua  205 Dec 13 20:07 HOME-timeseries
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin]$
```

**Comment by Akanksha2511** [comment]
Can you please send me what you get by following commands :
`(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$ ls`

`(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$ HOME-pairwise`

`(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$ python HOME-pairwise`

**Comment by Linhua-Sun** [comment]
Thank you so much:
```
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin]$cd /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$ls
HOME  HOME.egg-info  README.md  build  dist  environment.yml  requirements.txt  saved_model  scripts  setup.py  testcase  training_data
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$HOME-pairwise
Traceback (most recent call last):
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.4', 'HOME-pairwise')
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1518, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/HOME-pairwise' not found in metadata at '/data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME/HOME.egg-info'
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$
```

**Comment by Akanksha2511** [comment]
The issue is it's not able to find `HOME-pairwise` in scripts. Can you please do the following to check if the binaries are present in script: 
`(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME]$  cd ./scripts/` and then `ls`

Also, please just try deactivating and reactivatiing your virtual env.

**Comment by Linhua-Sun** [comment]
You can see there are those binaries files.
```
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY/HOME/scripts]$l
total 56K
-rwxrwxrwx 1 linhua linhua 1.3K Dec 13 17:24 HOME_R_time.R
-rwxrwxrwx 1 linhua linhua 1.4K Dec 13 17:24 HOME_R.R
-rwxrwxrwx 1 linhua linhua  23K Dec 13 17:24 HOME-timeseries
-rwxrwxrwx 1 linhua linhua  22K Dec 13 17:24 HOME-pairwise
```
And I exit the shell and login in again, then reactivate my virtual env. But it still not works. And new errors generated after I chmod 777 the  HOME-pairwise and other files. I see that they don't have run permission.
```
Traceback (most recent call last):
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.4', 'HOME-pairwise')
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/HOME-0.4-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 18, in <module>

  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pandas/__init__.py", line 48, in <module>
    from pandas.io.api import *
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pandas/io/api.py", line 15, in <module>
    from pandas.io.packers import read_msgpack, to_msgpack
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pandas/io/packers.py", line 63, in <module>
    from pandas.msgpack import Unpacker as _Unpacker, Packer as _Packer, ExtType
  File "/data1/linhua/QIANLAB/PROJECT/TEST_PY/hh/lib/python2.7/site-packages/pandas/msgpack/__init__.py", line 21, in <module>
    from pandas.msgpack._packer import Packer
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/linhua/.linuxbrew/lib/libstdc++.so.6)
```

Thank you very much!

**Comment by Akanksha2511** [comment]
I guess you have installed inside your virtual environment. Can you please make sure HOME directory is installed "outside" the virtual env as below. 
![file_structure](https://user-images.githubusercontent.com/12772210/33947067-6bab350e-e05e-11e7-82c1-0865f0f42ea3.png)
 HOME_env is the virtual env name. In your case it will be hh.

**Comment by Linhua-Sun** [comment]
Wow, it seems to be the key point. I will have a try immediately.

**Comment by Linhua-Sun** [comment]
Sorry for the wrong reply. I am sure that HOME directory is installed "outside" the virtual env. You can see following:
```
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY]$l
total 8.0K
drwxrwxr-x  5 linhua linhua 4.0K Dec 13 17:22 hh
drwxrwxr-x 11 linhua linhua 4.0K Dec 13 17:27 HOME
(hh) [linhua@localhost /data1/linhua/QIANLAB/PROJECT/TEST_PY]$l *
hh:
total 16K
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:22 include
drwxrwxr-x 3 linhua linhua 4.0K Dec 13 17:22 lib
-rw-rw-r-- 1 linhua linhua   60 Dec 13 17:22 pip-selfcheck.json
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 20:07 bin

HOME:
total 60K
-rw-rw-r-- 1 linhua linhua   74 Dec 13 17:24 requirements.txt
-rw-rw-r-- 1 linhua linhua  146 Dec 13 17:24 environment.yml
-rw-rw-r-- 1 linhua linhua  13K Dec 13 17:24 README.md
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:24 HOME
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:24 saved_model
-rw-rw-r-- 1 linhua linhua  511 Dec 13 17:24 setup.py
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:24 scripts
drwxrwxr-x 4 linhua linhua 4.0K Dec 13 17:24 testcase
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:24 training_data
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:27 HOME.egg-info
drwxrwxr-x 5 linhua linhua 4.0K Dec 13 17:27 build
drwxrwxr-x 2 linhua linhua 4.0K Dec 13 17:27 dist
```

**Comment by Akanksha2511** [comment]
Hi, your virtual environment doesn't seem to have local and share directory as in the example I sent earlier. Also, it has an extra include directory. Can you please make sure you follow the steps for setting up the virtual environment correctly. Thanks
