### ISSUE TITLE
multiprocessing range parameter

### ISSUE THREAD

**Issue by bhofmei** [ListerLab/HOME#26]
I've been trying to use this for the time-series capabilities but I get this error **every** time.

```
Traceback (most recent call last):
  File "/home/bth29393/.local/bin/HOME-timeseries", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==0.7', 'HOME-timeseries')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 750, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1534, in run_script
  File "/home/bth29393/.local/lib/python2.7/site-packages/HOME-0.7-py2.7.egg/EGG-INFO/scripts/HOME-timeseries", line 490, in <module>
    
  File "/usr/local/apps/eb/Python/2.7.14-foss-2018a/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
Exception: range parameter must be finite.
```
Looking at the code, I don't think they affects the output. But I can't be sure.

Running HOME v0.7 with correct requirements.

**Comment by Akanksha2511** [comment]
Hi, 
Are you getting the output DMRs?. Seems like a numpy issue with nan values, but if you are getting the output it should be fine. Otherwise will need to have a look at the input files.

**Comment by bhofmei** [comment]
thanks for responding so quickly! i do get output. but idk how to be sure im getting *all* the output

**Comment by Akanksha2511** [comment]
I think it should be ok..but to be 100% sure I will have to look at the files, so if you want to can share the files with me
