### ISSUE TITLE
HOME_DMR error

### ISSUE THREAD

**Issue by zhangaicen** [ListerLab/HOME#33]
Hi Akanksha，
I tried to used HOME to identify DMR from two samples without replicates, my command is: 
HOME-pairwise -t CG -i ~/methylation/findDMR_HOME_input.txt -o ./ -md 200 --BSSeeker2 --delta 0.3 --minc 5 -npp 8
and the the .txt is:
ploidy_4  /user/zac/methylation/NovaA-210121/CGmap/4n_merge.CGmap.gz
ploidy_8  /user/zac/methylation/NovaA-210121/CGmap/8n_merge.CGmap.gz
but it returns to some error: 
The output (if any) follows:

Traceback (most recent call last):
  File "/gss1/home/zqq20190923/miniconda3/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==1.0.0', 'HOME-pairwise')
  File "/gss1/home/zqq20190923/miniconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/gss1/home/zqq20190923/miniconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/gss1/home/zqq20190923/miniconda3/lib/python2.7/site-packages/HOME-1.0.0-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 492, in <module>

NameError: name 'status' is not defined
 Temp directory at output path already exist.... please clean up and rerun
 Temp directory at output path already exist.... please clean up and rerun

So could you tell me what is wrong with my HOME?
Thank you.

**Comment by Akanksha2511** [comment]
Hi, it seems that you have not deleted the temp directory could you please clean it and run it again. 

Thanks, 
Akanksha
