### ISSUE TITLE
NameError: name 'status' is not defined

### ISSUE THREAD

**Issue by malonzm1** [ListerLab/HOME#37]
Hi,

I'm trying to run HOME, `HOME-pairwise 	-t CG 	-i ./neg_files.txt	-o ./results/neg_2`, however I encounter the error below:

Traceback (most recent call last):
  File "/scratch/work/malonzm1/.conda_envs/HOME/bin/HOME-pairwise", line 4, in <module>
    __import__('pkg_resources').run_script('HOME==1.0.0', 'HOME-pairwise')
  File "/scratch/work/malonzm1/.conda_envs/HOME/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/scratch/work/malonzm1/.conda_envs/HOME/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/scratch/work/malonzm1/.conda_envs/HOME/lib/python2.7/site-packages/HOME-1.0.0-py2.7.egg/EGG-INFO/scripts/HOME-pairwise", line 492, in <module>
    
NameError: name 'status' is not defined

Pls. advise. Thanks!

**Comment by Akanksha2511** [comment]
Hi, 

Could you please provide the full path of the input and output file instead of relative path in the command above and run it again. 

Thanks, 
Akanksha

**Comment by malonzm1** [comment]
Hi,

Thanks. I provided the full path to the input and output files but it still gives the same error.
